RedHatQE/openshift-virtualization-tests

tests/infrastructure/golden_images/update_boot_source/test_ssp_data_import_crons.py, tests/storage/checkups/conftest.py, tests/storage/test_data_import_cron.py, utilities/constants.py
Due to changes in [wrapper](https://github.com/RedHatQE/openshift-python-wrapper/pull/2279), we introduce this patch
=>   Fix DataImportCron tests based on wrapper fixes

.github/workflows/labeler.yml
Add checkout action to fetch the labeler config
NONE
=> workflow, labeler: Add checkout action to fetch the labeler config

.github/labeler.yml, .github/workflows/labeler.yml
Use proper formatting, enable sync-labels and drop checkout step.
=> labeler: Adjust workflow and configuration

README.md, tests/chaos/conftest.py, tests/conftest.py, tests/deprecated_api/test_deprecation_audit_logs.py, tests/install_upgrade_operators/node_component/test_deploy_cnv_on_subset_of_nodes_sanity.py, tests/install_upgrade_operators/node_component/utils.py, tests/storage/cdi_import/test_import_http.py, utilities/constants.py, utilities/hco.py
=> Rename master utils fixtures and use control-plane in place of master when possible

tox.ini
=> Add 4.19.0 to jira target versions

tests/observability/metrics/conftest.py, tests/observability/metrics/test_cdi_metrics.py, tests/observability/metrics/utils.py
Test for metric kubevirt_cdi_storageprofile_info.
=> Test for kubevirt_cdi_storageprofile_info

tests/storage/test_cdi_certificate.py, tests/storage/vm_export/test_vm_export.py
- remove `test_upload_after_certs_renewal` from gating
- change timeout to posibly reduce flakiness of this test
- add vmexport test back to gating
=> Storage: adjust gating tests

tests/virt/cluster/aaq/test_arq.py, tests/virt/cluster/common_templates/general/test_base_template.py, tests/virt/cluster/common_templates/general/test_diskless_vm.py, tests/virt/cluster/migration_and_maintenance/test_evictionstrategy.py, tests/virt/cluster/migration_and_maintenance/test_migration_policy.py, tests/virt/cluster/operator_tests/test_ssp_custom_resources.py, tests/virt/cluster/resource_limits/test_auto_resource_limits.py, tests/virt/cluster/vm_cloning/test_vm_cloning.py
Review virt/cluster tests to ensure only relevant tests are part of T2 gating and the execution time continues to stay reasonable.
=> Review virt cluster T2 gating tests

tests/install_upgrade_operators/must_gather/conftest.py, tests/install_upgrade_operators/must_gather/test_must_gather.py
=> remove skip_no_rhcos from test repository

tests/virt/cluster/longevity_tests/utils.py, tests/virt/node/general/test_oom.py
Change multiprocessing to threads
=> [Virt] Change multiprocessing to threads

tests/conftest.py, tests/install_upgrade_operators/security/scc/test_default_scc.py, tests/observability/metrics/test_vms_metrics.py, tests/storage/cdi_upload/test_upload.py, tests/storage/cdi_upload/test_upload_virtctl.py, tests/storage/test_cdi_config.py, tests/virt/cluster/common_templates/general/test_base_template.py
=> remove fixture skip_not_openshift

tests/virt/OWNERS, tests/virt/cluster/OWNERS, tests/virt/node/OWNERS
=> Add Vasiliy as sigowner for virt

uv.lock
=> update packages in uv.lock

tests/network/nmstate/test_nncp_maxunavailable.py
Test is not marked with sno marker. So it won't be executed on sno.
=> remove skip_if_not_three_nodes fixture

utilities/hco.py
Use 'with ResourceEditorValidateHCOReconcile' for the correct teardown
=> fix for update_hco_annotations function teardown

tests/network/host_network/vlan/conftest.py, tests/network/host_network/vlan/test_vlan_on_host.py
=> remove skip_insufficient_nodes

tests/install_upgrade_operators/must_gather/conftest.py
=> add node for network_device call

OWNERS
=> Add vsibirsk and dshchedr as root approvers

Makefile, tox.ini
=> target branch for 4.18

utilities/virt.py
Adjust according to https://github.com/kubevirt/kubevirt/pull/13939
=>  Fix SSH - Change separators in virtctl port-forward

utilities/OWNERS
=> update owners file

utilities/virt.py
=> [4.18] SSH: add type to virtctl port-forward

pyproject.toml, uv.lock
=> pin openshift-python-wrapper to 4.18

uv.lock
=> [4.18] update packages

tests/after_cluster_deploy_sanity/test_after_cluster_deploy_sanity.py
=> add a cluster health check to check for cluster common cpus

tests/storage/constants.py, tests/storage/restricted_namespace_cloning/conftest.py, tests/storage/restricted_namespace_cloning/constants.py, tests/storage/restricted_namespace_cloning/test_restricted_namespace_cloning.py, tests/storage/restricted_namespace_cloning/test_restricted_namespace_cloning_vms.py, tests/storage/restricted_namespace_cloning/utils.py, tests/storage/snapshots/conftest.py, tests/storage/snapshots/test_snapshots.py, tests/storage/utils.py
- remove the test cases that are covered by other tests
- add permissions to get and list PVCs when needed
=>  Storage: refactor restricted_namespace_cloning tests, reduce execution time from 60 minutes to 20

tests/data_protection/OWNERS, tests/storage/OWNERS, tests/virt/OWNERS
=> don't require root approvers for storage and virt

conftest.py, pytest.ini, tests/conftest.py, tests/virt/node/workload_density/test_swap.py
add swap marker (exclude from tier2 list)
remove programmatic skip
=>  [VIRT] Updates for swap test

tests/observability/metrics/test_vms_metrics.py
This is just some minor improvement to use monitor utility to get metric value when I look at the test code
=> [Improvement]:Use utilits.monitoring to get prometheus metric value

tests/network/conftest.py, tests/network/connectivity/test_pod_network.py, tests/network/migration/test_migration.py
=> change ipv4/ipv6 matrix related skips to fail

tests/network/connectivity/conftest.py, tests/network/connectivity/test_ovs_linux_bridge.py, tests/network/general/test_dhcp6_configurations_on_ipv4_single_stack_cluster.py
=> update skip fixtures to use pytest.fail

tox.ini, uv.lock
=> update tox for mark-automated-polarion

tox.ini, uv.lock
=> update packages and tox

tests/virt/cluster/common_templates/conftest.py, tests/virt/cluster/common_templates/rhel/test_rhel_os_support.py, tests/virt/cluster/common_templates/utils.py, tests/virt/cluster/vm_lifecycle/test_vm_run_strategy.py, tests/virt/node/hotplug/test_cpu_memory_hotplug.py
remove skips like skip on specific os version, etc
=> [virt] remove test config related programmatic skips

conftest.py, pytest.ini, tests/network/user_defined_network/test_user_defined_network.py, uv.lock
=> [cnv-4.18] Enable UDN tests by removing "udn" marker, add ns label and update condition

tests/network/conftest.py
Add DPDK validation to network sanity check
Add DPDK validation to network sanity check
The network_sanity fixture was updated to include validation for
DPDK support. If any test is marked with the dpdk marker, it checks
whether the cluster supports running DPDK tests by verifying the
existence of the dpdk performance profile. If the profile does not
exist, the test execution is halted with an appropriate error message.
The logging was updated to reflect the DPDK validation status.
This is a follow up PR after: #287 , which I used the same logic as it was for skipping, but now for assertion.
=> Add DPDK validation to network sanity check

tests/network/conftest.py
Refactor network_sanity to log all failures before exiting
Refactored network_sanity to first verify all network requirements and accumulate failures before exiting. This ensures all missing components are logged, providing better visibility into multiple issues at once.
The verification logic for multi-NIC and DPDK support is now structured into separate functions for improved readability. The failure messages are collected and logged collectively before terminating the test run.
This PR is a follow up for:
https://github.com/RedHatQE/openshift-virtualization-tests/pull/408#pullrequestreview-2669521318
=> Refactor network_sanity to log all failures before exiting

pytest.ini, tests/conftest.py, tests/infrastructure/golden_images/conftest.py, tests/infrastructure/golden_images/test_common_templates_data_volumes.py, tests/infrastructure/instance_types/test_common_vm_instancetype.py, tests/infrastructure/sap/test_sap_hana_vm.py, tests/infrastructure/tekton/test_tekton_custom_ns.py, tests/infrastructure/tekton/test_tekton_pipeline_disk_uploader.py, tests/infrastructure/workload_availability/remediation_fencing/conftest.py, tests/infrastructure/workload_availability/remediation_fencing/test_nodehealthcheck_default_remediation.py, tests/infrastructure/workload_availability/remediation_fencing/test_nodehealthcheck_fenceagent_remediation.py, tests/infrastructure/workload_availability/remediation_fencing_mhc/test_ha_vm.py, tests/virt/node/workload_density/test_free_page_reporting.py
Add skips for Infra component
https://issues.redhat.com/browse/CNV-55885
=> [Infrastructure] Replace conditional skips with pytest markers

tests/install_upgrade_operators/crds_cluster_readers_role/test_crds_cluster_readers_role.py
=> Replace jira 51065 to 58119

tests/observability/metrics/conftest.py, tests/observability/metrics/test_metrics.py
Test for metric kubevirt_allocatable_nodes.
https://issues.redhat.com/browse/CNV-54807
=> Test for kubevirt_allocatable_nodes

tests/observability/metrics/conftest.py, tests/observability/metrics/constants.py, tests/observability/metrics/test_vms_metrics.py, tests/observability/metrics/utils.py
Test for kubevirt_vm_vnic_info
and kubevirt_vm_vnic_info
=> Test for vnic_info metrics

tests/infrastructure/instance_types/test_cpu_memory_hotplug_instancetype.py, tests/virt/cluster/aaq/conftest.py, tests/virt/node/conftest.py
=>  update clean_up_migration_jobs function

tests/virt/cluster/common_templates/conftest.py, tests/virt/node/migration_and_maintenance/test_post_copy_migration.py, tox.ini
=> [virt] update jiras to 4.18

conftest.py, tests/virt/conftest.py, tests/virt/node/high_performance_vm/test_numa.py
cherry-pick of https://github.com/RedHatQE/openshift-virtualization-tests/pull/489
=> [virt] update virt-sanity checks (#489)

tests/observability/metrics/conftest.py, tests/observability/metrics/test_metrics.py
Test for metric kubevirt_allocatable_nodes.
https://issues.redhat.com/browse/CNV-58155
=> CherryPicked: [cnv-4.18] Test for kubevirt_allocatable_nodes (#466)

tests/storage/test_libguestfs.py
The fix is a more reliable way to exit libguestfs to avoid flaky
=> [Storage] Fix libguestfs test

tests/network/conftest.py
Add service mesh verification to network sanity check
Add service mesh verification to network sanity check
The network_sanity fixture now checks for the service mesh operator.
It verifies if the istio-system namespace exists to ensure the
operator is installed.
If the namespace is missing, a failure message is appended
indicating that the operator is not installed.
This PR is based on: #472
=> Add service mesh verification to network sanity check

tests/virt/node/high_performance_vm/test_high_performance_templates.py
=> [virt] fix high_resource_vm in hight peft template test

pytest.ini, tests/network/service_mesh/test_service_mesh.py
=> [cnv-4.18] Add service_mesh marker

tests/infrastructure/tekton/conftest.py, tests/infrastructure/tekton/test_tekton_pipeline_disk_uploader.py
- Add support for export-source-kind PVC
- Refactor code to support Datasource with snapshot
=> Refactor disk-uploader task tests

tests/network/conftest.py
Validate jumbo frame support in network sanity check
Validate jumbo frame support in network sanity check
Added a check to ensure the cluster supports jumbo frame tests.
If the network MTU is too low, a failure message is recorded.
This prevents tests from running when the network is not capable
of handling jumbo frames.
This PR is based on: #478
=> Validate jumbo frame support in network sanity check

uv.lock
=> update wrapper to 11.0.39

uv.lock
=> [4.18] update wrapper to 4.18.4

tests/network/conftest.py
Validate SR-IOV support in network sanity checks
Validate SR-IOV support in network sanity checks
Added a check to ensure SR-IOV is supported before running tests.
The validation ensures the required namespace exists, preventing
misconfigured test runs.
=> Validate SR-IOV support in network sanity checks

uv.lock
=> update uv packages cnv-4.18

uv.lock
=> update uv packages

tests/install_upgrade_operators/conftest.py, tests/install_upgrade_operators/daemonset/test_daemonset_params.py, tests/install_upgrade_operators/must_gather/test_must_gather_vms.py, tests/install_upgrade_operators/pod_validation/test_pod_spec.py, tests/install_upgrade_operators/security/scc/test_cnv_pods_scc.py
=> [IUO] update jiras to 4.18

utilities/constants.py
Add support for AAQ in resource conditions
=> Add support for AAQ in resource conditions

tests/chaos/snapshot/conftest.py, tests/data_protection/oadp/conftest.py, tests/data_protection/oadp/utils.py, tests/infrastructure/golden_images/update_boot_source/test_latest_rhel_image.py, tests/storage/cdi_import/conftest.py, tests/storage/cdi_import/test_import_http.py, tests/storage/cdi_import/test_import_registry.py, tests/storage/cdi_upload/test_upload_virtctl.py, tests/storage/conftest.py, tests/storage/restricted_namespace_cloning/conftest.py, tests/storage/restricted_namespace_cloning/test_restricted_namespace_cloning_vms.py, tests/storage/test_online_resize.py, tests/storage/test_wffc.py, tests/utils.py, utilities/storage.py
=> Storage: use memory_guest instead of memory_requests

tests/storage/restricted_namespace_cloning/conftest.py, tests/storage/restricted_namespace_cloning/test_restricted_namespace_cloning.py, tests/storage/restricted_namespace_cloning/test_restricted_namespace_cloning_vms.py
=> Storage: fail if no unprivileged_client instead of skip

tests/network/utils.py
Refactor assert_ssh_alive command
Refactor assert_ssh_alive command
Update assert_ssh_alive to use a more efficient ss
command for checking established SSH connections.
Tis PR is a follow up of:
https://github.com/RedHatQE/openshift-virtualization-tests/pull/582#discussion_r2012509020
=> Refactor assert_ssh_alive command

tests/virt/node/workload_density/test_swap.py
* [VIRT] Updates for swap test
add swap marker (remove programmatic skip)
* increase memory loadage and timeout
increase memory loadage and timeout
=> [4.18] [VIRT] Updates for swap test (#372)

conftest.py, tests/global_config.py, utilities/constants.py
* collect data from other namespaces depending on component name
* remove goldenimage namespace
* rename function
* [pre-commit.ci] auto fixes from pre-commit.com hooks
for more information, see https://pre-commit.ci
---------
=> collect data from other namespaces depending on component name (#199)

tests/conftest.py, tests/infrastructure/instance_types/conftest.py, tests/infrastructure/instance_types/supported_os/test_rhel_os.py, tests/infrastructure/instance_types/utils.py, tests/virt/cluster/common_templates/centos/test_centos_os_support.py, tests/virt/cluster/common_templates/conftest.py, tests/virt/cluster/common_templates/fedora/test_fedora_os_support.py, tests/virt/cluster/common_templates/rhel/test_rhel_os_support.py, tests/virt/cluster/common_templates/utils.py, tests/virt/cluster/common_templates/windows/test_windows_os_support.py, tests/virt/cluster/conftest.py, tests/virt/cluster/general/test_smbios.py, tests/virt/cluster/utils.py, tests/virt/node/gpu/gpu_pci_passthrough/test_rhel_vm_with_gpu_pci_passthrough.py, tests/virt/node/gpu/vgpu/test_rhel_vm_with_vgpu.py, tests/virt/utils.py, utilities/virt.py
Add/Update VM creation, features, migration, and deletion tests 
https://issues.redhat.com/browse/CNV-41856
=> Add rhel10 guest tests using instancetype/prefernce

tests/infrastructure/vhostmd/test_vhostmd.py
https://issues.redhat.com/browse/CNV-52354
=> Moving vhostmd tests to tier2

tests/global_config_ibm_spectrum_sc.py, utilities/constants.py
=> update IBM sc name

utilities/constants.py
=> Remove unused const WSL2_DV_SIZE

utilities/network.py
We still observe sporadic timeouts in this method. This change should be backported to all supported versions.
=> Increase timeout in BridgeNodeNetworkConfigurationPolicy.to_dict

tests/infrastructure/instance_types/test_common_vm_preference.py
https://issues.redhat.com/browse/CNV-56939
=> Improve logic to handle cluster preference with CPU spread options

uv.lock
=> [cnv-4.18]update uv packages

tests/virt/node/descheduler/conftest.py
Use correct ImageDigestMirrorSet name
=> [VIRT] Fix descheduler teardown

conftest.py, tests/global_config.py, tests/global_config_aws.py, tests/global_config_ibm_spectrum_sc.py, tests/global_config_interop_sno.py, tests/global_config_lvms.py, tests/global_config_nfs.py, tests/global_config_oci.py, tests/global_config_rh_it.py, tests/global_config_sno.py, tests/global_config_sno_hpp.py, utilities/constants.py, utilities/pytest_matrix_utils.py, utilities/pytest_utils.py
Backport: https://github.com/RedHatQE/openshift-virtualization-tests/pull/491
=> [4.18] Add storage capabilities to the storage class matrix #491

tests/global_config.py, utilities/constants.py
Add rhel 9.6 OS matrix
https://issues.redhat.com/browse/CNV-51560
=> Add Rhel 9.6 OS to rhel_os_matrix

tests/network/OWNERS
=> Add Edi as CNV Network approver

tests/infrastructure/instance_types/supported_os/test_rhel_os.py
https://issues.redhat.com/browse/CNV-54688
=> Add basic RHEL10 Instancetype VM lifecycle tests to smoke

tests/install_upgrade_operators/must_gather/test_must_gather_vms.py
This Jira won't be fixed in 4.18 - https://issues.redhat.com/browse/CNV-58483
The start fix version will be 4.19.
Have to adjust the d/s automation accordingly for 4.18 branch.
Blocking our CI.
https://issues.redhat.com/browse/CNV-60113
=> Remove jira reference 58483

containers/fedora/build.sh, containers/utility/Dockerfile
Add s390x support for test container image
Add support to build following containers on s390x:
qe-cnv-tests-fedora
qe-cnv-tests-net-util-container
=> s390x support for test container image

tests/network/bond/test_l2_bridge_over_bond.py
Use the fixtures to state the VMs in an async manner (i.e. do not wait for them to actually reach running state) and wait on both VMs in the test itself.
@sbahar619 , this is the follow up I promised after the last changes in the bond package.
=> tests, net, bond: Start VMs in parallel for faster test execution

tests/virt/OWNERS, tests/virt/cluster/OWNERS, tests/virt/node/OWNERS
combine cluster and node reviewers in parent folder
=> [VIRT] combine cluster and node reviewers list

tests/install_upgrade_operators/csv/csv_permissions_audit/csv-permissions.yaml, utilities/constants.py
Update csv and additional operator from clusterpermissions
https://issues.redhat.com/browse/CNV-59848
=> Update csv permissions and operators

tox.ini
=> add 4.20.0 target ver to tox

pyproject.toml, uv.lock
=> update poetry and pyproject

pytest.ini, tests/virt/cluster/aaq/test_aaq_allocation_methods.py, tests/virt/cluster/aaq/test_acrq.py, tests/virt/cluster/aaq/test_arq.py, tests/virt/cluster/common_templates/rhel/test_rhel_os_support.py, tests/virt/cluster/migration_and_maintenance/test_evictionstrategy.py, tests/virt/cluster/migration_and_maintenance/test_migration_policy.py, tests/virt/cluster/operator_tests/test_critical_pods.py, tests/virt/cluster/operator_tests/test_ssp_custom_resources.py, tests/virt/cluster/vm_cloning/test_vm_cloning.py, tests/virt/cluster/vm_lifecycle/test_restart.py, tests/virt/cluster/vm_lifecycle/test_vm_run_strategy.py
Add a new arm pytest marker to categorize ARM-based tests  and mark related tests
https://issues.redhat.com/browse/CNV-56490
=>  Virt: Add arm marker and mark related tests

tests/virt/node/cpu_sockets_threads/test_cpu_support_sockets_threads.py, tests/virt/node/general/test_cloud_init_vm.py, tests/virt/node/general/test_container_disk_vm.py, tests/virt/node/general/test_networkinterfacemultiqueue_feature.py
Add arm related test cases on virt-node component
https://issues.redhat.com/browse/CNV-58921
=> Virt: Add arm related tests on virt-node component

pyproject.toml, uv.lock
=> [4.18] Update uv packages

tests/network/OWNERS
In order to be counted for the minimum lgtm counts, add EdDev to the review list.
=> tests, net, owners: Add EdDev to the reviewers list

tests/install_upgrade_operators/hco_enablement_golden_image_updates/test_custom_golden_images_namespace.py, tests/install_upgrade_operators/resource_params/test_hco_status_conditions.py, tests/install_upgrade_operators/strict_reconciliation/test_operator_defaults.py
=> [IUO] update gating tests

tests/global_config.py
=> Fix smoke - point instance type to pick rhel10 datasource instead of rhel10-beta

OWNERS, utilities/OWNERS
=> Add `rnetser` in `OWNERS` files and remove `dbasunag`

tests/install_upgrade_operators/hco_enablement_golden_image_updates/test_custom_golden_images_namespace.py, tests/install_upgrade_operators/resource_params/test_hco_status_conditions.py, tests/install_upgrade_operators/strict_reconciliation/test_operator_defaults.py
Cherry pick from [main](https://github.com/RedHatQE/openshift-virtualization-tests/pull/869)
=> [4.18][IUO] update gating tests

tests/virt/cluster/common_templates/conftest.py, tests/virt/cluster/common_templates/windows/test_windows_os_support.py
Keeping qemu guest agent related cases test, because the bug have been fixed.
=> Virt: Remove xfail_guest_agent_info_on_win2025 cause bug fixed

libs/net/netattachdef.py, libs/net/traffic_generator.py, libs/net/vmspec.py, libs/vm/factory.py, libs/vm/spec.py, libs/vm/vm.py, pyproject.toml, tests/network/bond/test_l2_bridge_over_bond.py, tests/network/cluster_addons_operator/test_network_addons_operator.py, tests/network/libs/apimachinery.py, tests/network/libs/cloudinit.py, tests/network/libs/nodenetworkconfigurationpolicy.py, tests/network/localnet/conftest.py, tests/network/localnet/liblocalnet.py, tests/network/localnet/test_localnet.py
Cherry-pick of the following PRs:
#218 
#733 
#754 
#876 
#464
=> [cnv-4.18] backport localnet test and its dependencies

tests/infrastructure/tekton/conftest.py, tests/infrastructure/tekton/test_tekton_pipeline_disk_uploader.py
- Add support for export-source-kind PVC
- Refactor code to support Datasource with snapshot
=> Refactor disk-uploader task tests (#313)

libs/vm/vm.py, tests/network/bond/test_bond_modes.py, tests/network/bond/test_l2_bridge_over_bond.py, tests/network/connectivity/test_pod_network.py, tests/network/connectivity/utils.py, tests/network/dry_run/test_dry_run_kubemacpool.py, tests/network/flat_overlay/utils.py, tests/network/jumbo_frame/conftest.py, tests/network/jumbo_frame/test_bond.py, tests/network/jumbo_frame/test_bridge.py, tests/network/kubemacpool/conftest.py, tests/network/l2_bridge/conftest.py, tests/network/l2_bridge/test_bridge_nic_hot_plug.py, tests/network/l2_bridge/test_ovs_bridge.py, tests/network/l2_bridge/utils.py, tests/network/macspoof/conftest.py, tests/network/migration/test_masquerade_connectivity_after_migration.py, tests/network/migration/test_migration.py, tests/network/network_policy/test_network_policy.py, tests/network/nmstate/conftest.py, tests/network/nmstate/test_connectivity_after_nmstate_changes.py, tests/network/ovs_bond/conftest.py, tests/network/sriov/conftest.py, tests/network/sriov/test_sriov.py, tests/network/user_defined_network/test_user_defined_network.py, utilities/virt.py
This PR cherry-pick the following PRs:
#782 
#795
#830
#793
#842
#826
#838
#822
#840
#836
#844
#828
#846
#820
=> [cnv-4.18] Backport Drop usage of 'running_vm'

tests/install_upgrade_operators/relationship_labels/test_all_cnv_resources.py
Cherry pick from https://github.com/RedHatQE/openshift-virtualization-tests/pull/1044/files
=> [4.18] Allowlist istio cm for OSSM

tests/virt/node/gpu/gpu_pci_passthrough/conftest.py
Manual cherry-pick of https://github.com/RedHatQE/openshift-virtualization-tests/pull/1089
added sampler to retry node config validation
(there's race condition window when DS reports all pods are Running and the config is acually applied on all nodes)
=> [4.18][virt] fix gpu node configuration validation (#1089)

tests/storage/cdi_import/test_import_http.py, tests/storage/cdi_upload/test_upload_virtctl.py
=> Replace hardcoded image size

tests/deprecated_api/test_deprecation_audit_logs.py, tests/virt/cluster/common_templates/general/test_base_template.py
- test_vmi_annotations
- test_deprecated_apis_in_audit_logs
NONE
=> test: enable more tests for s390x

tests/virt/conftest.py, tests/virt/utils.py
=> revert changes for non_existent_mdev_bus_nodes (#1251)

tests/virt/conftest.py, tests/virt/utils.py
=> revert changes for non_existent_mdev_bus_nodes (#1251) (#1328)

tests/infrastructure/instance_types/test_common_vm_instancetype.py, tests/infrastructure/workload_availability/remediation_fencing/conftest.py, tests/infrastructure/workload_availability/remediation_fencing/test_nodehealthcheck_default_remediation.py
=> [Infrastructure][4.19] Fix jira references

tests/virt/constants.py, tests/virt/node/migration_and_maintenance/test_post_copy_migration.py, tests/virt/upgrade/conftest.py, tests/virt/upgrade/test_upgrade_virt.py, tests/virt/utils.py
cherry-pick of #1336 - post-copy migration test in upgrade scope
=> [4.19] [VIRT] Add post-copy migration test to upgrade scope (#1336)

tests/install_upgrade_operators/must_gather/conftest.py, utilities/must_gather.py
cherry-pick https://github.com/RedHatQE/openshift-virtualization-tests/pull/1510 into cnv-4.19
=> CherryPicked: [cnv-4.19] [CNV-66035]increase must-gather timeout values to prevent collection failures

tests/storage/golden_image/test_cached_snapshots.py, utilities/storage.py, uv.lock
* Update wrapper to 11.0.90 
* **Refactor**
* Use `source_ref` for `DataVolume` creation from `DataSource`
=> Update wrapper to 11.0.90, adjust smoke tests

tests/storage/cdi_import/test_import_registry.py
Cherry-pick: https://github.com/RedHatQE/openshift-virtualization-tests/pull/1750
=> [4.18] Storage: remove duplicate public registry test (#1750)

tests/install_upgrade_operators/feature_gates/test_default_featuregates.py
=> [4.19]Remove verified CNV-63030.

tests/storage/cdi_upload/conftest.py, tests/storage/cdi_upload/test_upload_virtctl.py, tests/storage/conftest.py, tests/storage/test_cdi_certificate.py, utilities/pytest_matrix_utils.py
cherry-pick https://github.com/RedHatQE/openshift-virtualization-tests/pull/2099 into cnv-4.18
=> [4.18] Storage: replace skip_if_sc_volume_binding_mode_is_wffc fixture with immediate_matrix
