- Dockerfile
Install packages without the docs.
Keep the image size small
> Update Dockerfile with nodocs

- tests/network/user_defined_network/test_user_defined_network.py
Update test name to reflect accurate behavior after live migration
Renamed the test `test_ip_address_is_preserved_during_live_migration` to `test_ip_address_is_preserved_after_live_migration` to improve clarity.
This ensures the test name accurately reflects its purpose: verifying that the IP address is preserved after live migration. The update enhances readability and aligns the test name with its intended behavior.
> Update test name to reflect accurate behavior after live migration

- libs/net/udn.py
- libs/net/vmspec.py
- tests/network/user_defined_network/test_user_defined_network.py
net: Refactor the UDN tests and move generic helpers to libs.net
Cover several topics to cleanup the udn test module, including typing coverage:
- Introduce vmspec module and move helpers from tests to it
- Introduce an UDN module with a recommended timeout const
- Refactor lookup-iface helpers
- Move the UDN primary net creation helper to libs.net
- Diff between failing to find iface in spec and status
- Generalize the lookup for the primary network
It is recommended to review the changes one commit at a time.
NONE
> net: Refactor the UDN tests and move generic helpers to libs.net

- tests/network/cluster_addons_operator/test_network_addons_operator.py
Starting 4.18, kubevirtIpamController is defaultly added to ClusterNetworkAddonsOperator (as part of the UserDefinedNetwork effort).
This fix also resolves a tier2 test that currently fails on 4.18.
> Support the addition of kubevirtIpamController to ClusterNetworkAddonsOperator

- tests/infrastructure/golden_images/update_boot_source/test_ssp_data_import_crons.py
Change the method we used to create a new data import cron
Changed the way the data import cron is created to deploy the resource from a complete new object
Latest DataImportCron object added required resource on pull_method, which is blocking the creation of the current resource.
In addition since it is not a required resource, created a PR for the wrapper we use - https://github.com/RedHatQE/openshift-python-wrapper/pull/2280
Failing test class `TestDataImportCronDefaultStorageClass`
> Pull method created data import cron

- libs/net/netattachdef.py
After this member was removed from the parent class in the wrapper it became useless here, and resulted in some tests failing.
In addition to network tests, this fix was also verified on virt tests (test_dedicated_live_migration_network.py) that create `NetworkAttachmentDefinition` resources.
> Remove unused timeout member from NetworkAttachmentDefinition class

- tests/network/flat_overlay/utils.py
- utilities/virt.py
Fix failures of localnet tests, by searching for the exact relevant nc process.
The need for this fix came up after `test_multi_network_policy_is_effective_post_migration` failed with
```
18:20:52  2025-01-13T16:20:41.275569 pyhelper_utils.shell INFO [SSH][vmc-flat-l2-1736785156-5188904] Executed: pgrep nc || true, rc:0, out: 5
...
...
18:20:52    File "/cnv-tests/tests/network/flat_overlay/conftest.py", line 373, in vmc_nc_connection_initialization
18:20:52      start_nc_response_on_vm(vm=vmc_flat_overlay, num_connections=CONNECTION_REQUESTS, flat_l2_port=flat_l2_port)
18:20:52    File "/cnv-tests/tests/network/flat_overlay/utils.py", line 113, in start_nc_response_on_vm
18:20:52      fetch_pid_from_linux_vm(vm=vm, process_name="nc")
18:20:52    File "/cnv-tests/utilities/virt.py", line …
```
> Locate the exact nc process

- .github/labeler.yml
- .github/workflows/labeler.yml
Introduce the "labeler" github-action
Start using the labeler action in order to mark PRs with labels based on the location of the changed files.
This is intended to assist identify codebase areas that changed so the relevant contributors/reviewers can filter them out and attend them.
As the first example, add the `sig-network` label to changes related to the network tests & libraries.
Ref: https://github.com/actions/labeler
Per https://github.com/actions/labeler?tab=readme-ov-file#initial-set-up-of-the-labeler-action , we will need to merge it as is and examine it on follow up PRs.
NONE
> labeler: Introduce the "labeler" github-action

- libs/net/traffic_generator.py
- tests/network/user_defined_network/test_user_defined_network.py
Add Server and Client classes and UDN test for connectivity preservation after live migration
Add UDN test for connectivity post live migration
This commit introduces a test for UDN to ensure connectivity is preserved
during live migration scenarios.
Introducing server and client fixtures using the newly created
classes to test TCP connectivity between two VMs. The fixtures
sets up the connection between 2 VMs using iperf3.
Additionally, a test named test_connectivity_is_preserved_after_live_migration
is added to verify that TCP connectivity is preserved after live migration.
This ensures the integrity of network connections during VM migration scenarios.
This automation is based on the test case CNV-11427.
Add classes for iperf3 network testing
The Server and Client classes have been …
>   Add Server and Client classes and UDN test for connectivity preservation after live migration

- tests/observability/metrics/conftest.py
- tests/observability/metrics/constants.py
- tests/observability/metrics/test_metrics.py
Fixing test for kubevirt_api_request_deprecated_total. The test changed the VirtualMachine import which led to failures to all other tests that came after it.
In order to avoid changing the import I created an instance of VirtualMachine with deprecated api version and did calls that raised the metric value.
> Fixing kubevirt_api_request_deprecated_total

- tests/chaos/conftest.py
- tests/chaos/migration/test_migration.py
- tests/chaos/utils.py
During the teardown phase, the virt-launcher Pod is deleted along with the VM and will not be recreated.
However, pod_deleting_process_recover still attempts to locate the virt-launcher Pod, and raising a ResourceNotFoundError
> [Chaos] Fix test_pod_delete_migration with virt_launcher failure

- tests/virt/cluster/longevity_tests/conftest.py
- tests/virt/conftest.py
- tests/virt/node/conftest.py
- tests/virt/node/general/test_wsl2.py
`nodes_intel_cpu_model` fixture is not needed anymore after introduction of `modern_cpu_for_migration fixture`
https://issues.redhat.com/browse/CNV-48680
> [virt] remove nodes_intel_cpu_model fixture

- tests/infrastructure/tekton/conftest.py
- tests/infrastructure/tekton/test_tekton_custom_ns.py
- tests/infrastructure/tekton/test_tekton_pipeline_disk_uploader.py
- tests/infrastructure/tekton/utils.py
Tekton task disk-uploader is introduced. This patch creates a basic pipeline with disk-uploader task and run the pipeline with defined parameters.
> Include disk-uploader pipeline in tekton tests

- tests/conftest.py
- tests/install_upgrade_operators/product_install/conftest.py
- tests/install_upgrade_operators/product_upgrade/conftest.py
- tests/install_upgrade_operators/product_upgrade/utils.py
- tests/install_upgrade_operators/utils.py
- tests/virt/upgrade/conftest.py
- tests/virt/upgrade/utils.py
- utilities/operator.py
_**"Cherry pick" from 4.16 branch.**_
1. eus_hco_target_version should use fixtures from the same scope(might fail optin test)
2. cnv_version fixture is redudant - can be removed.
3. change the names of fixtures and util function to match their purpose:
getting the cnv name of the target version
the name changes:
```
hco_target_version -> hco_target_version_csv_name
eus_hco_target_version -> eus_hco_target_version_csv_name
get_hco_version -> get_hco_csv_name_by_version
```
post upgrade test using this fixture may fail.
In addition the fixture/naming test is misleading.
> Fix eus_hco_target_version

- tests/network/checkup_framework/test_checkup_framework.py
- tests/network/checkup_framework/utils.py
1. Revert "Skip checkup framework tests due to CNV-55124".
2. Iterate over all job's status conditions to find the relevant one.
3. Remove ping-parser bug marker after verifying its fix.
This fix is based on the change in checkup presented in https://github.com/kiagnose/kiagnose/pull/264
> Fix checkup failures and remove bug markers

- tests/infrastructure/vm_console_proxy/conftest.py
- tests/infrastructure/vm_console_proxy/constants.py
- tests/infrastructure/vm_console_proxy/test_vm_console_proxy.py
- tests/infrastructure/vm_console_proxy/utils.py
- Updated vm_console_proxy_service_account_role_binding fixture to reference ClusterRole instead of Role
- Introduced a new helper function assert_resource_status_and_wait_for_availability to check resource availability status in tests.
https://issues.redhat.com/browse/CNV-34769
> Refactor VM console proxy test

- tests/storage/checkups/conftest.py
`DataImportCron` creates a `DataSource`, but it is not supposed to clean it up, so we must clean it up on teardown.
> Storage: cleanup DataSource in checkup tests

- tests/conftest.py
- tests/observability/metrics/test_general_metrics.py
kubevirt_hco_single_stack_ipv6 test failed duo
to wrong logic, fixed in this PR.
https://issues.redhat.com/browse/CNV-56293
> Triaging kubevirt_hco_single_stack_ipv6 failure

- tests/install_upgrade_operators/strict_reconciliation/test_hco_default_cpu_model.py
- tests/utils.py
- utilities/constants.py
Use defaultCPUModel parameter instead of json patch annotations
> Set the cluster default cpu by using defaultCPUModel param in HCO

- tests/virt/cluster/common_templates/conftest.py
- tests/virt/cluster/common_templates/windows/test_windows_os_support.py
win2025 guest agent case failed continuously, bug fixed on qemu-ga but not get the latest build, skip it until there's the latest build
CNV-Tracker: https://issues.redhat.com/browse/CNV-52655
> Virt:Skip guest agent info tests on win2025 until get latest build

- tests/infrastructure/instance_types/test_common_vm_instancetype.py
GN instance type  is not available
https://github.com/kubevirt/common-instancetypes/commit/e92465229845769950efd0edee4d1e3ac4f44f0b
> Remove tests covering gn1

- utilities/must_gather.py
subprocess.run would wait indefinitely when timeout=None. We should explicitly set timeout for must-gather calls.
> must-gather collection can hang on a cluster , so add timeout for run_command() call

- tests/virt/node/descheduler/conftest.py
- utilities/operator.py
remove create_folder_and_mirror_file
create_folder_and_mirror_file is only used in descheduler `generated_descheduler_icsp_idms`, it can be removed to reduce code complexity
Make the code more readable
An alternate to use `get_generated_icsp_idms` was considered, this require more complex changes and testing since it defines `pull_secret` in a condition, as such I decided to focus this PR only on the removal of the function.
> remove create_folder_and_mirror_file

- utilities/virt.py
Supported options from @0xFelix:
4.18: [type/]name[.namespace] starting point
4.19: type/name[.namespace] preferred, name[.namespace] still working with a warning
4.20: type/name[/namespace], backward compatibility for type/name.namespace
4.21: type/name[/namespace] only
> SSH: use .namespace - compatible with 4.19 and 4.20/4.99

- conftest.py
- pytest.ini
- tests/network/user_defined_network/test_user_defined_network.py
Enable UDN tests by removing "udn" marker
Enable UDN tests by removing "udn" marker
Removed the "udn" marker from the EXCLUDE_MARKER_FROM_TIER2_MARKER
list in conftest.py to enable UDN tests as part of Tier 2.
Removed the "udn" marker definition from pytest.ini
and the usage of "udn" marker in test_user_defined_network.py.
UDN tests are now enabled by default and will run as
part of the Tier 2 tests without needing explicit inclusion.
Add fixture for UDN namespace with required label
Added udn_namespace fixture to create a namespace
with the required label at namespace creation.
Refactor readiness check for UDN status
Replaced wait_for_network_ready() with wait_for_condition()
to support the new NetworkAllocationSucceeded status.
The old method uses NETWORK_READY, which is outdated.
It …
> Enable UDN tests by removing "udn" marker, add ns label and update condition

- utilities/infra.py
This is just some minor improvement to use KUBECONFIG constant in infra.py instead of a string value.
> [Minor change]:Use KUBECONFIG constant

- tests/observability/metrics/test_vms_metrics.py
Test for kubevirt_vm_create_date_timestamp_seconds metric.
> Test for kubevirt_vm_create_date_timestamp_seconds

- tests/conftest.py
- tests/observability/metrics/test_migration_metrics.py
* Triage kubevirt_vmi_migration_metrics
Triaging kubevirt_vmi_migration_metrics failures
by changing the query to check for the last_over_time by 5 mins, also changed the scope of fixtures in order to reduce the test execution tim.
* Added test for kubevirt_vmi_migration_dirty_memory_rate_bytes
Added test to TestKubevirtVmiMigrationMetrics test class because it has the same setup.
* Added cpu_for_migration to vm fixutre
Added cpu_for_migration to vm for migration
* Added cpu_for_migration to vm fixutre
Added cpu_for_migration to vm for migration
https://issues.redhat.com/browse/CNV-57551
> CherryPicked: [cnv-4.18] Triage kubevirt_vmi_migration_metrics (#316)

- tests/install_upgrade_operators/strict_reconciliation/test_hco_default_cpu_model.py
Tests for validating HCO cryptopolicy are updated now to run successfully for ARM cluster as well.
https://issues.redhat.com/browse/CNV-32277
> Update crypto-policy tests for ARM cluster

- conftest.py
- tox.ini
Fixing the upgrade_custom collection.
In addition adding upgrade-custom runs to tox.
Mypy requires line 397, because of: 
```
ocp_upgrade_test = None
cnv_upgrade_test_with_prod_src = None
cnv_upgrade_test_no_prod_src = None
eus_upgrade_test = None
```
> Fix upgrade_custom collection

- tests/conftest.py
- tests/install_upgrade_operators/must_gather/conftest.py
- utilities/network.py
Cherry pick from [4.19 ](https://github.com/RedHatQE/openshift-virtualization-tests/pull/418)
Tests that are using VM with bridge interface is flaky,
because on slow clusters the node might not update yet with allocatable/capacity status.
It affect IUO must gather tests, and network upgrade tests.
> [4.18] Wait for node update when creating linux bridge 

- tests/network/user_defined_network/test_user_defined_network.py
Align Layer2UserDefinedNetwork with UDN API changes
Replace ipam_lifecycle with ipam dict for flexible IPAM
configuration and improved compatibility with UDN API changes.
This PR depends on:
https://github.com/RedHatQE/openshift-python-wrapper/pull/2329
>  Align Layer2UserDefinedNetwork with UDN API changes

- tests/network/conftest.py
Refactor network_sanity fixture comment for generalization
Updated the network_sanity fixture docstring to be more generic. Removed specific details about multi-NIC verification to prepare for future expansions where additional network checks will be added.
This PR is a follow up for:
https://github.com/RedHatQE/openshift-virtualization-tests/pull/408#pullrequestreview-2669521318
> Refactor network_sanity fixture comment for generalization

- tests/global_config.py
- tests/infrastructure/golden_images/update_boot_source/test_boot_sources_vm.py
- tests/infrastructure/golden_images/update_boot_source/test_ssp_common_templates_boot_sources.py
- tests/infrastructure/golden_images/utils.py
- utilities/infra.py
Add test for data sources with instance types and preferences
Adding test for all existing data sources we import from the data import cron.
Since centos-10/rhel-10 don't have templates we can't add them to the testing matrix, as such we should create a test that creates a VM using instance types and preferences for the Data Source.
Add coverage for all existing data import cron, we are currentelly missing rhel10 and centos10 because they do not have a template 
Next release rhel10-beta naming will be needed to change to rhel-10
https://issues.redhat.com/browse/CNV-41859
> Add tests for data sources with instance types

- tests/observability/metrics/conftest.py
Adding new vmi_pod label to check to the
test for kubevirt_vmi_info metric.
> Add vmi_pod check for kubevirt_vmi_info

- tests/observability/metrics/test_migration_metrics.py
Remove migration_policy_with_bandwidth_scope_class fixture from TestKubevirtVmiMigrationMetrics test class.
https://issues.redhat.com/browse/CNV-58124
> Remove migration_policy_with_bandwidth

- containers/fedora/user-data
Fix persistent network interface naming issue in Fedora 41
Fix persistent network interface naming issue in Fedora 41
Added virt-customize to apply net.ifnames=0 kernel argument
to Fedora 41 image to resolve network interface persistent naming
issues.
Ref for the change introduced in Fedora41 that caused the issue this PR aim to solve:
https://docs.fedoraproject.org/en-US/fedora/latest/release-notes/sysadmin/?utm_source=chatgpt.com#consistent-device-naming-in-fedora-cloud
Some tests use cloud-init with networkData defining interfaces as eth0, eth1, etc. (ethX syntax). However, Fedora 41 enforces consistent network device naming (e.g., enp1s0), causing a mismatch with our current cloud-init implementation.
Currently more than 50% ot network tests failing because of this issue.
>  Fix persistent network interface naming issue in Fedora 41

- tests/network/checkup_framework/test_checkup_framework.py
Add tier3 marker to checkup framework tests
Add tier3 marker to checkup framework tests
Added the tier3 marker to checkup framework tests in
test_checkup_framework.py. This ensures proper test categorization
and filtering when running test suites.
> Add tier3 marker to checkup framework tests

- pytest.ini
- tests/network/service_mesh/test_service_mesh.py
Add service_mesh marker
Add service_mesh marker
Added the `service_mesh` marker to the `pytest.ini` file for tests
requiring the service mesh operator.
Replaced the incorrect `special_infra` marker with
`service_mesh` in the relevant test file. The `special_infra` marker
was replaced because the service mesh operator does not require any
special infrastructure or node-level configurations, making it
inaccurate for tests related to the service mesh.
> Add service_mesh marker

- pytest.ini
- tests/network/jumbo_frame/test_bond.py
- tests/network/jumbo_frame/test_bridge.py
- tests/network/jumbo_frame/test_pod_network_ovn.py
Add jumbo_frame marker and mark related tests
Add jumbo_frame marker and mark related tests
Added a new jumbo_frame pytest marker to categorize tests
requiring network configurations that support jumbo frames.
Marked existing jumbo frame related tests with the jumbo_frame
marker for better classification. Also, marked the jumbo frame
tests with the special_infra marker as they require infrastructure
network NICs to support jumbo frames.
> Add jumbo_frame marker and mark related tests

- tests/infrastructure/instance_types/test_vm_with_instance_and_pref.py
- tests/infrastructure/instance_types/utils.py
Instance type and preference runtime data is now stored under status and is no longer mutated into the VM Spec
- Move functions to utils and add hints
- Remove tests where we update RevisionName
https://issues.redhat.com/browse/CNV-46345
>  Instance type and preference runtime data is now stored under status and is no longer in VM Spec

- tests/network/conftest.py
Add IPv4 support check to network sanity validation
Add IPv4 support check to network sanity validation
Introduced a check to ensure the cluster supports
IPv4 before running relevant tests.
> Add IPv4 support check to network sanity validation

- tests/install_upgrade_operators/csv/csv_permissions_audit/csv-permissions.yaml
4.18.1 CSV permissions are not up to date
https://issues.redhat.com/browse/CNV-58340
>  Update csv permissions

- tests/network/utils.py
Replace deprecated netstat with ss
Replace deprecated netstat with ss
netstat is deprecated, so this updates assert_ssh_alive
to use ss instead. Functionality remains unchanged.
Currently 2 network tests are failing because of this issue:
test_ssh_vm_migration and test_ssh_alive_after_restart_nmstate_handler.
```
failed on setup with "timeout_sampler.TimeoutExpiredError: Timed Out: 30
Function: pyhelper_utils.shell.run_ssh_commands  Kwargs: {'host': <rrmngmnt.host.Host object at 0x7f92acfd11f0>, 'commands': [['sudo', 'netstat', '-tulpan', '|', 'grep', 'ssh']]}
Last exception: CommandExecFailed: Command: sudo netstat -tulpan | grep ssh - exec failed. Error: sudo: netstat: command not found
```
Quote from netstat manual page:
```
This program is mostly obsolete.  Replacement for netstat is …
```
> Replace deprecated netstat with ss

- conftest.py
- tests/global_config.py
- tests/global_config_aws.py
- tests/global_config_ibm_spectrum_sc.py
- tests/global_config_interop_sno.py
- tests/global_config_lvms.py
- tests/global_config_nfs.py
- tests/global_config_rh_it.py
- tests/global_config_sno.py
- tests/global_config_sno_hpp.py
- tests/storage/cdi_clone/test_clone.py
- utilities/constants.py
- utilities/pytest_matrix_utils.py
- utilities/pytest_utils.py
**Before this PR:** 
- Storage capability matix was built according to what is present in the cluster (i.e. VolumeSnapshotClass, or StorageClass's allowVolumeExpansion parameter)
**After this PR:**
- We explicitly list the storage capabilities and build the capability matrices according to the expected capability
- Making the `storage_class_matrix` values more explicit
>  Add storage capabilities to the storage class matrix

- tests/network/connectivity/test_ovs_linux_bridge.py
- tests/network/connectivity/test_pod_network.py
Towards stabilizing network tier-2 tests, and specifically the gating ones, this PR
- splits the pod network connectivity test to IPv4 and IPv6 cases
- marks the IPv6 tests with the ticket that trackes this limitation.
> Split pod network connectivity test per IP family

- utilities/network.py
CNV-19348 seems like it no longer appears, and it's not required to wait that long for the interfaces to be visible - including on bare-metal.
> Remove references to closed issue CNV-19348

- tests/install_upgrade_operators/must_gather/test_must_gather.py
At test_crd_resources test, if we will try to get non-served api version, The test will fail.
We need to test only the served ones.
Failures in 4.17 + 4.18 branches.
Starting from main because we need to apply it going forward as well
> [IUO] Skip non-served api versions

- tests/install_upgrade_operators/must_gather/test_must_gather.py
Cherry-pick.
At test_crd_resources test, if we will try to get non-served api version, The test will fail.
We need to test only the served ones.
> [4.18][IUO] Skip non-served api versions

- tests/network/upgrade/utils.py
- tests/virt/upgrade/conftest.py
Before upgrade, two tests fails consistently due to 4.18+ product changes.
**test_bridge_marker_before_upgrade**
The test trying to access the node with vm.vmi.node.instance....
Should use privleged_vmi.
**test_windows_vm_before_upgrade**
The test doesn't set RunStrategy, as required from 4.18+.
Run strategy has to be set.
https://issues.redhat.com/browse/CNV-58491
> [Upgrade] Fix network and virt pre-upgrade tests

- tests/observability/network/conftest.py
- tests/observability/utils.py
Triaging kubevirt_cnao_kubemacpool_manager_up
removed the util that waits for kubemacpool
for being in pending state because it makes the test flaky,
sometime these pods deleted because the image switching and
it fails the test on the setup because it doesn't find them.
https://issues.redhat.com/browse/CNV-57412
> [CherryPicked]: [cnv-4.18] Triaging kubevirt cnao kubemacpool manager up

- utilities/virt.py
Improve VM error assertion with detailed status output
Improve VM error assertion with detailed status output
Enhanced assert_vm_not_error_status to include full VM status details
in assertion errors. This provides better debugging information when a
VM enters an unexpected error state.
We have flakiness in our tests which fail on this assertion, logging the full VM status will give us the actual reason why the VM failed.
>  Improve VM error assertion with detailed status output

- tests/infrastructure/instance_types/test_update_vm_with_instancetype_preference.py
- tests/infrastructure/instance_types/test_vm_override_pref.py
- tests/infrastructure/instance_types/test_vm_preference.py
Code Improvement:
- VM to automatically use memory_guest from the instance type.Setting memory_guest manually will cause a conflict with the instance type.(VM field(s) spec.template.spec.domain.memory conflicts with selected instance type.)
- For preference only tests, replaced memory_requests with memory_guest.
> Allocate VM memory from memory_guest 

- tests/install_upgrade_operators/conftest.py
- tests/install_upgrade_operators/daemonset/test_daemonset_params.py
- tests/install_upgrade_operators/pod_validation/test_pod_spec.py
- tests/install_upgrade_operators/security/scc/test_cnv_pods_scc.py
This component got removed recently - https://issues.redhat.com/browse/CNV-53226
Should be removed from automation 4.19 & 4.99 gating tests for  won't fail.
https://issues.redhat.com/browse/CNV-59082
> [IUO] Remove Ipam resources and Jira CNV-53226

- tests/network/upgrade/utils.py
- tests/virt/upgrade/conftest.py
Cherry pick from https://github.com/RedHatQE/openshift-virtualization-tests/pull/621
Before upgrade, two tests fails consistently due to 4.18+ product changes.
**test_bridge_marker_before_upgrade**
The test trying to access the node with vm.vmi.node.instance....
Should use privleged_vmi.
**test_windows_vm_before_upgrade**
The test doesn't set RunStrategy, as required from 4.18+.
Run strategy has to be set.
> [4.19][Upgrade] Fix network and virt pre-upgrade tests

- tests/global_config_oci.py
- utilities/constants.py
To run the tests with OCI storage:
`uv run pytest --storage-class-matrix=oci-bv --tc-file=tests/global_config_oci.py ...`
> Add OCI storage class

- README.md
- conftest.py
- pytest.ini
- tests/conftest.py
- tests/install_upgrade_operators/product_upgrade/conftest.py
- tests/install_upgrade_operators/product_upgrade/test_eus_upgrade.py
- tests/install_upgrade_operators/product_upgrade/test_upgrade.py
- tests/install_upgrade_operators/product_upgrade/test_upgrade_iuo.py
- tests/network/upgrade/test_upgrade_network.py
- tests/storage/upgrade/test_upgrade_storage.py
- tests/upgrade_params.py
- tests/virt/upgrade/test_upgrade_virt.py
- tests/virt/upgrade_custom/aaq/test_upgrade_virt_aaq.py
Use explicit upgrade marker to detect test related to an upgrade lane(ocp/cnv/eus).
If performing OCP upgrade, keep only the tests with pytest.mark.ocp_upgrade.
If performing EUS upgrade, keep only the tests with pytest.mark.eus_upgrade.
If performing CNV upgrade, keep only the tests with pytest.mark.cnv_upgrade.
In addition,for cnv upgrade, determine if we are running the cnv upgrade test for production source or for stage/osbs.
It will allow to choose specific tests per upgrade type, which is more flexible when adding/removing upgrade tests,
and know excatly which should be running.
In addition, we can get rid of the programmatic skips. 
https://issues.redhat.com/browse/CNV-57035
> Use upgrade markers explicitly for test collection

- tests/network/connectivity/test_ovs_linux_bridge.py
- tests/network/connectivity/test_pod_network.py
Towards stabilizing network tier-2 tests, and specifically the gating ones, this PR
- splits the pod network connectivity test to IPv4 and IPv6 cases
- marks the IPv6 tests with the ticket that tracks this limitation.
> [4.18] Resolve IPv6 gating tests in non-supporting clusters

- tests/install_upgrade_operators/strict_reconciliation/test_hco_related_objects.py
- utilities/constants.py
In 4.18+ versions, this hco-bearer-token secret is added to hco relatedobjects.
We need to add it to ALL_HCO_RELATED_OBJECTS list so our matrix test won't fail.
In addition, its really hard to understand from the log which related objects are added.
Changed the test to log only the new related objects.
> [IUO] add hco-bearer-auth secret to HCO resources

- tests/virt/cluster/aaq/conftest.py
- tests/virt/cluster/aaq/utils.py
- tests/virt/node/owner_references/test_vm_owner_references.py
- tests/virt/upgrade_custom/aaq/conftest.py
- tests/virt/utils.py
added step to wait for virt-launcher pod to appear before calling vm.vmi.virt_launcher_pod
> [virt] fix aaq gating flake

- tests/infrastructure/vm_console_proxy/conftest.py
- tests/infrastructure/vm_console_proxy/test_vm_console_proxy.py
- tests/install_upgrade_operators/constants.py
Replace any place that uses the spec.featureGates.DeployVMConsoleProxy field, with spec.DeployVMConsoleProxy
Removed "nonRoot" const as well since its not being used.
https://issues.redhat.com/browse/CNV-52378
> Deprecate deployVMConsoleProxy feature gate

- tests/conftest.py
- utilities/storage.py
Currently, when we are switching to ocs-virt sc before an upgrade, we are deleting the bootsources as well.
For 4.18+, switching the sc should be enough.
https://issues.redhat.com/browse/CNV-56878
> Update default storage class setup for upgrade

- README.md
- conftest.py
- tests/install_upgrade_operators/product_upgrade/conftest.py
- utilities/operator.py
Cherry pick from 4.17.
With candidate/nightly channel being added, upon CNV upgrade we should be able too choose A channel to pull the target image from.
Relevant for CNV upgrade only.
EUS should always use stable.
> [Upgrade] Allow user to choose subscription channel

- tests/network/cluster_addons_operator/test_network_addons_operator.py
- tests/network/libs/nodenetworkconfigurationpolicy.py
Introducing a new NodeNetworkConfigurationPolicy (NNCP) resource to the libs/net library. This resource is meant to replace usage oc NNCP in the wrapper, which has large amount of functions added to it, which makes it difficult to add new helpers and functionalities.
The new NNCP is used in an existing test - test_linux_bridge_functionality.
As part of the initiative to create simpler resources and reduce dependency, this PR introduces a new NNCP resource in the lib directory.
> Utilities - Add NodeNetworkConfigurationPolicy resource to libs/net

- tests/global_config.py
- tests/global_config_arm64.py
- tests/os_params.py
- tests/virt/node/general/test_machinetype.py
- utilities/constants.py
add arm64 support for common template tests
only rhel9 templates supported now
https://issues.redhat.com/browse/CNV-59229
> [virt] add arm64 support for common template tests

- utilities/virt.py
fix `TimeoutSampler` usage in `get_oc_image_info` (fails on first exception catched)
`failed on setup with "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"`
now should correctly re-try for 10 sec getting image
Possibly should fix flake when first attempt fails due to connectivity issue
> [virt] fix get_oc_image_info sampler

- README.md
- conftest.py
- tests/install_upgrade_operators/product_upgrade/conftest.py
- utilities/operator.py
Cherry pick from 4.17.
With candidate/nightly channel being added, upon CNV upgrade we should be able too choose A channel to pull the target image from.
Relevant for CNV upgrade only.
EUS should always use stable.
> [4.18][Upgrade] Allow user to choose subscription channel

- tests/install_upgrade_operators/product_upgrade/conftest.py
- tests/install_upgrade_operators/product_upgrade/test_upgrade.py
KubeVirtDeprecatedAPIRequested alert - fired because worker's MCP fails to update and we collect must gather - which in turn collecting VirtualMachineInstancePresets which is deprecated API.
So on compact clusters - we should wait only for "master" MCP upgrade.
https://issues.redhat.com/browse/CNV-56379
>  [Upgrade] Modify cnv upgrade MCP check for osbs source

- pyproject.toml
- tests/network/libs/nodenetworkconfigurationpolicy.py
When mutating an existing NNCP object, it is common to wait for a
condition status of success (condition type "Available").
However, it has been observed or bare-metal clusters that the observed
condition is the previous one and is not reflecting the actual state
after the spec update/patch.
In order to handle these cases, the condition timestamp is used to
assure it has been updated post the change.
Other alternatives have been found unsafe, like the option of waiting
for an intermediate state (e.g. "progressing"). It is unsafe because the
state is in transition and that can be quicker than the sampling
performed by the test tools.
The current NNCP object updates the spec only when performing the
clean-up step (on teardown). At that step the previous created
interfaces are being removed. …
> tests, net, libs, nncp: On update/patch, assure correct status update

- tests/install_upgrade_operators/product_upgrade/conftest.py
- tests/install_upgrade_operators/product_upgrade/test_upgrade.py
Cherry pick from https://github.com/RedHatQE/openshift-virtualization-tests/pull/737
KubeVirtDeprecatedAPIRequested alert - fired because worker's MCP fails to update and we collect must gather - which in turn collecting VirtualMachineInstancePresets which is deprecated API.
So on compact clusters - we should wait only for "master" MCP upgrade.
> [4.19][Upgrade] Modify cnv upgrade MCP check for osbs source

- tests/global_config_arm64.py
- utilities/constants.py
add storage_class_matrix to arm64 global config
arm clusters can now be deployed with hpp and trident storage classes
```
hostpath-csi-basic             kubevirt.io.hostpath-provisioner   Delete          WaitForFirstConsumer   false                  10h
hostpath-csi-pvc-block         kubevirt.io.hostpath-provisioner   Delete          WaitForFirstConsumer   false                  10h
trident-csi-nfs (default)      csi.trident.netapp.io              Delete          Immediate              true                   30m
```
> add storage_class_matrix to arm64 global config

- tests/network/bond/test_l2_bridge_over_bond.py
- tests/network/libs/apimachinery.py
- tests/network/libs/cloudinit.py
- tests/network/libs/nodenetworkconfigurationpolicy.py
Introduce network cloud-init data structure and use it 
Introduce a new data structure for network cloud-init.
It is aimed to replace the existing dict-based configuration.
Usage example:
```python
from tests.network.libs import cloudinit
nd = cloudinit.NetworkData(ethernets={
"eth0": EthernetDevice(
dhcp4=False,
addresses=["1.1.1.1/24", "d10:0:2::2"],
gateway6="d10:0:2::1",
)
})
nd_yaml = yaml.safe_dump(cloudinit.todict(netdata=nd), sort_keys=False)
cloudinit_dict = cloudinit.cloudinit(netdata=nd)
```
> tests, net, libs: Introduce network cloud-init data structure

- README.md
- utilities/constants.py
A new utility function has been introduced to dynamically select test images based on the system's architecture. This is controlled by the environment variable `OPENSHIFT_VIRTUALIZATION_TEST_IMAGES_ARCH`. Supported architectures include:
- `x86_64` (default)
The architecture-specific test images class is selected automatically based on the `OPENSHIFT_VIRTUALIZATION_TEST_IMAGES_ARCH` environment variable. If the variable is not set, the default architecture `x86_64` is used.
Ensure the environment variable is set correctly before running the tests:
```bash
export OPENSHIFT_VIRTUALIZATION_TEST_IMAGES_ARCH=<desired-architecture>
```
If an unsupported architecture is specified, a `ValueError` will be raised.
>  support for multiple archs for the Images class

- README.md
- conftest.py
- pytest.ini
- tests/conftest.py
- tests/install_upgrade_operators/product_upgrade/conftest.py
- tests/install_upgrade_operators/product_upgrade/test_eus_upgrade.py
- tests/install_upgrade_operators/product_upgrade/test_upgrade.py
- tests/install_upgrade_operators/product_upgrade/test_upgrade_iuo.py
- tests/network/upgrade/test_upgrade_network.py
- tests/storage/upgrade/test_upgrade_storage.py
- tests/upgrade_params.py
- tests/virt/upgrade/test_upgrade_virt.py
- tests/virt/upgrade_custom/aaq/test_upgrade_virt_aaq.py
- tox.ini
Cherry pick from [main](https://github.com/RedHatQE/openshift-virtualization-tests/pull/448)
Use explicit upgrade marker to detect test related to an upgrade lane(ocp/cnv/eus).
If performing OCP upgrade, keep only the tests with pytest.mark.ocp_upgrade.
If performing EUS upgrade, keep only the tests with pytest.mark.eus_upgrade.
If performing CNV upgrade, keep only the tests with pytest.mark.cnv_upgrade.
In addition,for cnv upgrade, determine if we are running the cnv upgrade test for production source or for stage/osbs.
It will allow to choose specific tests per upgrade type, which is more flexible when adding/removing upgrade tests,
and know excatly which should be running.
In addition, we can get rid of the programmatic skips. 
https://issues.redhat.com/browse/CNV-57035
> [4.18] Use upgrade markers expliciity for test collection

- tests/install_upgrade_operators/product_upgrade/test_upgrade.py
- tests/virt/upgrade/conftest.py
- tests/virt/upgrade/test_upgrade_virt.py
Add gating marker to some upgrade tests, to support candidate(prod) -> candidate(stage) upgrade test.
The test should create a VM with instancetype(OCS-virt), upgrade, and check that the VM is healthy.
Should be run with `-m gating --upgrade=cnv --cnv-image=<img> --cnv-version=<version> --cnv-channel=candidate`
The selected tests:
```
<Package cnv-tests>
<Package tests>
<Package virt>
<Package upgrade>
<Module test_upgrade_virt.py>
<Class TestUpgradeVirt>
<Function test_is_vm_running_before_upgrade>
<Function test_vm_ssh_before_upgrade>
<Function test_vm_console_before_upgrade>
<Package install_upgrade_operators>
<Package product_upgrade>
<Module test_upgrade.py>
<Class TestUpgrade>
<Function test_cnv_upgrade_process>
<Package virt>
<Package upgrade>
<Module test_upgrade_virt.py>
<Class …
```
> [4.19][Upgrade] Adjust automation to support gating upgrade test

- tests/install_upgrade_operators/strict_reconciliation/conftest.py
- tests/install_upgrade_operators/strict_reconciliation/test_hco_related_objects.py
Currently hco-bearer-auth resource have reconciling bug.
Until its fixed, the automation should skip it.
> [IUO] Ignore hco-bearer-token resource if jira open

- tests/virt/node/general/test_legacy_machinetype.py
- tests/virt/node/general/test_machinetype.py
- tests/virt/utils.py
When test arm64 related cases, we use `global_config_arm64.py` as global configuration file, which not include `rhel-8-10` matrix_os, so it will failed when test machine_type cases.
So the purpose of this change is to separate `test_legacy_machinetype` as python file to avoid it impacts machine_type cases within arm64 tests
>   [Virt] Separate test_legacy_machinetype as test_legacy_machinetype.py

- tests/install_upgrade_operators/strict_reconciliation/conftest.py
- tests/install_upgrade_operators/strict_reconciliation/test_hco_related_objects.py
Cherry-pick from [main](https://github.com/RedHatQE/openshift-virtualization-tests/pull/768)
Currently hco-bearer-auth resource have reconciling bug.
Until its fixed, the automation should skip it.
> [4.18][IUO] Ignore hco-bearer-token resource if jira open

- tests/network/service_mesh/conftest.py
- tests/network/service_mesh/test_service_mesh.py
- tests/network/utils.py
OSSM moved from ver. 2 to 3. This fix adjusts to ver. 3 by enabling gateway injection, which is performed by labeling the work namespace with the matching label {istio-injection: enabled}.
>  Fix ServiceMesh tests and adjust to OSSM 3

- tests/install_upgrade_operators/must_gather/conftest.py
- utilities/must_gather.py
Fixing two issues with must gather.
1. Must gather collected both at failure point & IUO tests.But each time we run must-gather, it results in this message:
> error: Warning: spec.nodeSelector[node-role.kubernetes.io/master]: use "node-role.kubernetes.io/control-plane" instead
**Solution:** We should use control-plane selector.
can be done by passing specific node name/ setting up a node selector.
2. Currently, --since-time and --timeout flags are passed after "–" options seperator:
> oc adm must-gather --dest-dir=$PWD/regular --image=registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel9@sha256:520577044baddc484233e22feede7c67d72b18958ac36811367ee58c4ffe2a0f -- --since=0s --timeout=900s  /usr/bin/gather --vm-details
**Solution**: They should be passed before the "–". …
>  Must gather fix flags and node role

- tests/virt/constants.py
Upstream limit was increased recently:
https://github.com/kubevirt/kubevirt/pull/13545
so updating the value accordingly.
> [VIRT] increase memory limits for virtqemud

- tests/install_upgrade_operators/must_gather/conftest.py
- utilities/must_gather.py
Cherry pick from https://github.com/RedHatQE/openshift-virtualization-tests/pull/705
Fixing two issues with must gather.
1. Must gather collected both at failure point & IUO tests.But each time we run must-gather, it results in this message:
> error: Warning: spec.nodeSelector[node-role.kubernetes.io/master]: use "node-role.kubernetes.io/control-plane" instead
**Solution:** We should use control-plane selector.
can be done by passing specific node name/ setting up a node selector.
2. Currently, --since-time and --timeout flags are passed after "–" options seperator:
> oc adm must-gather --dest-dir=$PWD/regular --image=registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel9@sha256:520577044baddc484233e22feede7c67d72b18958ac36811367ee58c4ffe2a0f -- --since=0s --timeout=900s …
> [4.18]Must gather fix flags and node role

- tests/network/l2_bridge/conftest.py
- tests/network/l2_bridge/test_bridge_nic_hot_plug.py
- tests/network/l2_bridge/test_ovs_bridge.py
- tests/network/l2_bridge/utils.py
`running_vm` is performing multiple checks to assure correct VM start. However, these checks are not required for the network tests.
For the network tests, a successful VM start is one that:
- Reaches ready status (i.e. a VMI in running phase).
- Reaches `AgentConnected` condition status (i.e. cloud-init stage succeeded based on the Fedora image setup).
This is an optimization to reduce observed flakiness on VM startup and simplify the overall maintenance (e.g. the use of a common helper that covers many aspects of a VM startup cycle forces all its users to the same logic, even though that logic is not of interest).
> tests, net, l2_bridge: Drop usage of 'running_vm'

- libs/vm/vm.py
- tests/network/bond/test_l2_bridge_over_bond.py
- tests/network/connectivity/test_pod_network.py
- tests/network/connectivity/utils.py
- tests/network/user_defined_network/test_user_defined_network.py
- utilities/virt.py
Replace the `wait_for_guest_agent` function in `utilities/virt` module
with a direct call to the wrapper implementation and a method in the
`VirtualMachineForTests` class.
Add the same method to the newer `VirtualMachineBase` under `libs/vm`.
Switch all usages of the underlying general `wait_for_condition` with
the `AGENT_CONNECTED` type, to the new method.
> Introduce `wait_for_agent_connected` method

- tests/network/libs/nodenetworkconfigurationpolicy.py
Currently, the default resource deployment is not waiting for the
resource to appear. We are interested for the NNCP resources to assure
that the resource exists before we continue.
This change assures that the `self.instance` exists and with it the
`status`.
On NNCP resource creation, the status and/or conditions may not yet be
populated. Assure such scenarios are treated.
> tests, net, libs, nncp:  Assure NNCP resource exists, status & conditions absense is treated correctly.

- libs/net/netattachdef.py
- libs/net/traffic_generator.py
- libs/net/vmspec.py
- libs/vm/factory.py
- libs/vm/spec.py
- libs/vm/vm.py
- pyproject.toml
- tests/network/libs/cloudinit.py
- tests/network/libs/nodenetworkconfigurationpolicy.py
- tests/network/localnet/conftest.py
- tests/network/localnet/liblocalnet.py
- tests/network/localnet/test_localnet.py
Add test for connectivity between localnet VMs
Add test for connectivity between localnet VMs
Introduced a new test to verify connectivity between VMs on the
localnet network. This test ensures that VMs within the localnet
network have connectivity.
https://issues.redhat.com/browse/CNV-55290
>  Add test for connectivity between localnet VMs

- pytest.ini
- tests/network/cluster_addons_operator/test_network_addons_operator.py
- tests/network/conftest.py
- tests/network/connectivity/test_ovs_linux_bridge.py
- tests/network/connectivity/test_pod_network.py
- tests/network/general/test_dhcp6_configurations_on_ipv4_single_stack_cluster.py
- tests/network/general/test_ip_family_services.py
- tests/network/general/test_network_naming.py
- tests/network/general/test_vm_ips_report.py
- tests/network/jumbo_frame/test_pod_network_ovn.py
- tests/network/kubemacpool/test_kubemacpool.py
- tests/network/migration/test_masquerade_connectivity_after_migration.py
- tests/network/network_policy/test_network_policy.py
- tests/network/ovs_optin/test_ovs_optin.py
- tests/network/service_mesh/test_service_mesh.py
- tests/network/single_node_tests/test_network_sno_deployment.py
- tests/network/user_defined_network/test_user_defined_network.py
Acceptance tests for new architectures, platforms etc. shouldn't depend on having extra NICs on the cluster nodes, except for the primary interface. In order to have satisfactory coveage in these tests, we mark all the these tests with the a new marker, which can and should be used for these types of tests.
> Mark network tests that don't require node's additional interfaces

- conftest.py
- pyproject.toml
- pytest.ini
- tests/network/rdp/test_rdp_for_exposed_vm_svc.py
- utilities/constants.py
- uv.lock
Added support for marking and handling quarantined tests, including custom status reporting and display in HTML test reports.
HTML test reports now include a "Quarantined Reason" column for better visibility of quarantined tests.
cherrypicks https://github.com/RedHatQE/openshift-virtualization-tests/pull/1128
> Add Quarentine support (cherrypick) cnv 4.18

- uv.lock
Causing issues with 4.18, duplicating logger calls, creating tons of logging and io issues.
Its causing failures due to high io and network latency.
[python-simple-logger](https://github.com/RedHatQE/python-simple-logger/compare/2.0.12...2.0.13) causing the issue.
The dep causing it - reverting creating new logger for each new resource call.
Updating should fix the issue.
> Update uv.lock file

- tests/install_upgrade_operators/csv/csv_permissions_audit/csv-permissions.yaml
ssp operator added deleted permission for servicemonitors
https://issues.redhat.com/browse/CNV-64253
> [IUO]Update 4.18.8 csv permissions

- utilities/constants.py
As we plan to improvise the code to build the image as given here https://github.com/RedHatQE/openshift-virtualization-tests/pull/1148#issuecomment-3003921765, till all those changes are done, to unblock s390x tests needing the qe-cnv-tests-fedora image, we point to image which is built from current changes on the PR #1148
@rnetser As discussed, created the PR.
cc: @stesrn @nestoracunablanco
> Update qe-cnv-tests-fedora image for s390x built from current changes on PR #1148

- utilities/virt.py
cherry pick and replacement [PR](https://github.com/RedHatQE/openshift-virtualization-tests/pull/1288)
> Update assert_vm_not_error_status: Wait for VM status to populate before asserting error state (#1018)

- tests/install_upgrade_operators/strict_reconciliation/conftest.py
- tests/observability/metrics/conftest.py
- tests/observability/metrics/test_instance_type_metrics.py
- tests/observability/metrics/test_metrics.py
- tests/observability/metrics/test_migration_metrics.py
There are 4.20 bugs being referenced on cnv-4.19 branch that is provoking tox check to fail. This PR is updating these IDs to the recently created cloned ones pointing to `CNV v4.19.z` version:
https://issues.redhat.com/browse/CNV-59679 --> https://issues.redhat.com/browse/CNV-64560
https://issues.redhat.com/browse/CNV-60672 --> https://issues.redhat.com/browse/CNV-64561
https://issues.redhat.com/browse/CNV-59552 --> https://issues.redhat.com/browse/CNV-64562
https://issues.redhat.com/browse/CNV-57777 --> https://issues.redhat.com/browse/CNV-64563
https://issues.redhat.com/browse/CNV-59518 --> https://issues.redhat.com/browse/CNV-64473
Check run locally and passed:
```
$ uv run pyutils-jira --config-file-path ~/jira.cfg --target-versions "vfuture,4.19.0,4.19.1,4.19.z" …
```
> [CNV-64474] Adjust Observability and IUO bugs IDs to 4.19.z fixVersion

- tests/storage/cdi_clone/conftest.py
- tests/storage/cdi_clone/test_clone.py
- tests/storage/conftest.py
- tests/storage/utils.py
- utilities/storage.py
Backport: https://github.com/RedHatQE/openshift-virtualization-tests/pull/1293 https://github.com/RedHatQE/openshift-virtualization-tests/pull/1242
> [4.19]  Update Cirros image to Fedora into test_clone.py

- tests/virt/node/migration_and_maintenance/test_post_copy_migration.py
The bug of cpu and memory hotplug with post-copy migration fixed on 4.20, but not plan to backport to previous version (the fix is very large) we plan to remove directly, if it fixed on previous version, we can add it back.
Manual cherry-pick #1362
> [4.18]Virt: Drop the cpu and memory hotplug cases with post-copy migration

- utilities/storage.py
Fix automation Tier2 tests by changing fedora image to cirros into utilities.
This change was previously made in order to use fedora image in some storage tests, but there are other tests that uses same function to create VMs from DVs with cirros.
Change Fedora image to Cirros. 
https://issues.redhat.com/browse/CNV-65260
> [4.19] Storage: fix create_vm_from_dv default args

- tests/observability/metrics/test_instance_type_metrics.py
The bug CNV-64561 fixed, removing the marker from tests.
https://issues.redhat.com/browse/CNV-66345
> [4.19]Remove jira marker for instanceType tests

- tests/network/user_defined_network/test_user_defined_network.py
test_connectivity_is_preserved_after_live_migration is flaky, and occasionally  fails when getting to providing the password for the console login. Until we stabilize it, it should not be part of gating. Currently we only observe it in 4.19; if needed, it will be handled in every relevant branch.
>  [4.19] Quarantine a flaky gating test

- tests/observability/metrics/test_metrics.py
- tests/observability/virt/conftest.py
- tests/observability/virt/test_virt_metrics_alerts.py
The test now is more simple then before, instead of changing image in daemonSet, I simply get the number of schedulable nodes and compare it with the prometheus result.
Also removed the alert that depends on this metric test since we are not testing alert in T2 anymore. first if a pod exists before deletion and in this way I make sure it won't fail in this part of the setup.
https://issues.redhat.com/browse/CNV-67428
> [4.19]Changing test implementation for metric kubevirt_nodes_with_kvm (#1731)

- utilities/virt.py
command syntax changed
the old syntax type/name.namespace
it should be type/name/namespace
upstream change: https://github.com/kubevirt/kubevirt/pull/15475
> [4.99] fix virtcl port-forward command

- tests/network/localnet/test_default_bridge.py
Tracked on CNV-67470.
This test is quarantined only in 4.19 and not in main because so far we experienced it failing only in 4.19, so we wouldn't want to quarantine (another) gating test if it's not a must.
This test failed because of the issue handled in this [PR](https://github.com/RedHatQE/openshift-virtualization-tests/pull/1939), so once it is merged, this test will be un-quarantined.
https://issues.redhat.com/browse/CNV-67470
> [4.19] Quarantine another test that fails because of the console login

- tests/observability/metrics/conftest.py
- tests/observability/metrics/test_metrics.py
The metric kube_daemonset_status_number_ready is kubernetes metric and not related to cnv and need to be removed.
> CherryPicked: [cnv-4.19] Remove test for kube_daemonset_status_number_ready (#1978)

- tests/observability/metrics/conftest.py
- tests/observability/metrics/test_cdi_metrics.py
- tests/observability/metrics/utils.py
- utilities/storage.py
Removing tests for metrics
kubevirt_cdi_clone_pods_high_restart
kubevirt_cdi_upload_pods_high_restart
kubevirt_cdi_operator_up
kubevirt_cdi_import_pods_high_restart
These metrics is recording rules that rely on
kubernetes metrics and not cnv.
Original PR: https://github.com/RedHatQE/openshift-virtualization-tests/pull/2025
https://issues.redhat.com/browse/CNV-69678
> CherryPicked: [cnv-4.18] Remove cdi metrics recording rules tests

- tests/conftest.py
- tests/observability/runbook_url/conftest.py
- tests/observability/runbook_url/test_runbook_url.py
Test for Upstream runbook urls is not relevant, this PR deletes it and simplify the runbook downstream urls test.
Original PR: https://github.com/RedHatQE/openshift-virtualization-tests/pull/1989
https://issues.redhat.com/browse/CNV-69515
> CherryPicked: [cnv-4.19] Deleted runbook US url test and improve DS runbook urls tes (#1989)

- tests/install_upgrade_operators/product_upgrade/conftest.py
- tests/install_upgrade_operators/product_upgrade/test_eus_upgrade.py
- tests/install_upgrade_operators/product_upgrade/utils.py
- utilities/operator.py
With  channels being added, we need extra logic to the EUS upgrade process.
What we need:
1. GetUpgradePath query modified to support channel, use it accordingly.
2. the target version can be from stable/candidate channel. ( for example 4.20.0). QE/ShippedLive versions are getting prioritized.
3.  The intermediate version should be from the stable channel.
The path is getting generated considering that.
Afterwards, we need to change the cnv subscription channel for the target version if its not "stable".
Started from 4.18 and not main to allow consistent 4.18 -> 4.20 testing.
will cherry pick to other branches afterwards
https://issues.redhat.com/browse/CNV-62122
> [Upgrade] Align EUS upgrade with additional channels

- tests/network/l2_bridge/test_l2_ovs_linux_bridge.py
The PR makes sure only the ovs-bridge instance of this test is quarantined, keeping the stable linux-bridge test running.
> [4.19] Quarantine flaky test_dhcp_broadcast[#ovs-bridge#]
